# @package _global_
defaults:
  - /task: benchmark
  - /dataset: synthetic
  - /split: all
  - /domain: rectangle
  - /preprocess: basic
  - /decompose: pod_svd
  - /coeff_post: none
  - /model: ridge
  - /eval: basic
  - /viz: basic
  - /uncertainty: gpr_mc
  - _self_

seed: 123
output_dir: outputs
tag: "_ex_pod_ridge"
run_dir: ${output_dir}/${task.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}${tag}_${hydra:job.num}

dataset:
  num_samples: 8
  height: 16
  width: 16

task:
  name: benchmark
  decompose_list: [pod_svd]
  coeff_post_list: [none]
  domain: rectangle

hydra:
  run:
    dir: ${run_dir}
  sweep:
    dir: ${output_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
