name: dict_learning
n_components: 32
alpha: 1.0
max_iter: 200
tol: 1.0e-6
fit_algorithm: lars
transform_algorithm: omp
transform_n_nonzero_coefs: 4
mask_policy: ignore_masked_points
positive_code: false
positive_dict: false
seed: 0
