# Hydra main config (skeleton)
defaults:
  - task: doctor
  - dataset: synthetic
  - split: all
  - domain: rectangle
  - preprocess: basic
  - decompose: fft2
  - codec: auto
  - offset_split: basic
  - coeff_post: none
  - model: ridge
  - train: basic
  - eval: basic
  - viz: basic
  - inference: basic
  - logging: basic
  - uncertainty: gpr_mc
  - clearml: basic
  - _self_

seed: 123
output:
  root: runs
  name: default
run_dir: ${output.root}/${output.name}/${task.name}

hydra:
  output_subdir: null
  run:
    dir: ${run_dir}
  sweep:
    dir: ${run_dir}
    subdir: ""
  job:
    config:
      override_dirname:
        kv_sep: "-"
        item_sep: "__"
        exclude_keys:
          - dataset.root
          - run_dir
          - output.root
          - output.name
          - task.decomposition_run_dir
          - task.preprocessing_run_dir
          - task.train_run_dir
